File "D:\python_itstep\структури_даних\11.11.py", line 224, in <module>     menu()   File "D:\python_itstep\структури_даних\11.11.py", line 205, in menu     linked_list.append() TypeError: LinkList.append() missing 1 required positional argument: 'data'